name: covidcapstone
description: Digital Contact Tracing for COVID-19

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  google_fonts:
# Firebase
#  firebase_core: ^0.7.0
  firebase_core_platform_interface: ^4.0.0
  firebase_database: ^6.0.0
  firebase_storage: ^8.0.0
  cloud_firestore: ^1.0.4
  firebase_auth: ^1.0.0
  firebase_auth_web: ^1.0.3
  firebase_messaging: ^9.1.1

  flutter_local_notifications: ^5.0.0
  url_launcher: ^6.0.3
  flutter_statusbarcolor: ^0.2.3
  lottie: ^1.0.1
  qr_flutter: ^3.1.0
  dio: ^4.0.0
  path_provider: ^2.0.1
  image_gallery_saver: ^1.6.6
  permission_handler: ^6.1.1
  image_downloader: ^0.30.0
  flare_flutter: ^2.0.6
  flutter_spinkit: ^5.0.0
  qr_code_scanner: ^0.3.5
  overlay_support: ^1.2.0
  jiffy: ^4.1.0
  font_awesome_flutter: ^8.8.1
  stacked: ^1.5.4
  stacked_services: ^0.3.2+1
  intl: ^0.17.0
  slide_to_confirm: ^0.0.6
  bluetooth_enable: ^0.1.1
  system_setting: ^0.1.3
  flutter_blue: ^0.8.0
  share: ^2.0.1
  shared_preferences: ^2.0.5
  flutter_inappwebview: ^5.3.2
  image_picker: 0.6.2
  toast: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
#  integration_test:
#    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "assets/android/background.png"
  adaptive_icon_foreground: "assets/android/foreground.png"

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/lotties/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
